export const SIGNUPSCREEN = "SIGNUPSCREEN";
export const SIGNINSCREEN = "SIGNINSCREEN";
export const HOMESCREEN = "HOMESCREEN";
export const TABNAVIGATOR = "TABNAVIGATOR";
export const INTROSCREEN = "INTROSCREEN";
export const FORGOTSCREEN = "FORGOTSCREEN";
export const OTPSCREEN = "OTPSCREEN";
export const NEWPASSWORDSCREEN = "NEWPASSWORDSCREEN";


